### ISSUE TITLE
Request for option to only include ff elements

### ISSUE THREAD

**Issue by JasCU100** [dteviot/EpubEditor#1]
Hello! I would like to request if there could be a feature/option to input certain elements that would be included in the epub? Basically, it's the opposite of the 'delete elements matching CSS' option that EpubEditor already has. Thank you very much!

**Comment by dteviot** [comment]
@JasCU100
Please provide more details.  
1. Where do these elements come from?  
2. Where are they placed?

**Comment by JasCU100** [comment]
> @JasCU100
> Please provide more details.
> 
> 1. Where do these elements come from?
> 2. Where are they placed?

For example in wordpress, usually the text that is scraped comes from div.site-content. It contains the text but also usually does not containt the comments, I think? So I think it would be good to just be able to select the elements wanted, therefore eliminating unnecessary ones. :)

**Comment by dteviot** [comment]
@JasCU100
Can you give me a worked example?  Something like:
1. I open site XXX in browser.
2. Run Web to Epub
3. This creates an Epub, at this point, it's adding div.site-content, but I want it to do YYYY instead.

**Comment by JasCU100** [comment]
For example:
1. I open [this](https://eatapplepies.com/mybookmarks/table-of-contents/) site
2. I run WebtoEpub
3. It outputs some unnecessary content (like link to next chapter, table of contents, etc. or comments) but I would like if it only inputs div.entry-content (where the text is located).

Sorry if I'm not clear in my explanations. Thank you.

**Comment by dteviot** [comment]
@JasCU100 
If you look at one of the pages from that site, say https://eatapplepies.com/tcf-chapter-1/
Yuo can see that the text of the chapter is a child of the "entry-content" element.
However, the 
* Next/Previous chapter buttons, and
* The Logon request 
are also children of the "entry-content" element.

So, WebToEpub is already picking the "entry-content" element.  To remove the Next/Previous, etc, you need to delete those child elements.
Have a read of https://dteviot.github.io/Projects/webToEpub_DefaultParser.html, it might make things a bit clearer.

**Comment by JasCU100** [comment]
Ohh thank you for clarifying it to me. :)
