### ISSUE TITLE
Not working on android mobile

### ISSUE THREAD

**Issue by pavan3999** [dteviot/EpubEditor#2]
Is it possible to run EpubEditor on mobile? I tried but main.html is not loading

**Comment by dteviot** [comment]
@pavan3999 
It depends on the web browser you're using.
Firefox probably won't work.
Note, as well as main.html, you'll also need jszip.min.js and the other files.

Suggested steps to use EpubEditor are:
1. Go to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing and download EpubEditor.zip
2. Unpack the zip file.
3. In file explorer, go to the files you unpacked from the zip and open the file main.html in your browser.

**Comment by pavan3999** [comment]
![Screenshot_20220428-200000](https://user-images.githubusercontent.com/23577468/165776093-95ed7fc5-8c2c-42e1-b34b-0cf905a0da84.jpg)
I trying in chrome but only loading page like in screenshot and can't select epub file too

**Comment by dteviot** [comment]
@pavan3999 
If it's not working, I can't help you any further.
Sorry, it wasn't designed to run on a phone or tablet.
To be honest, it was something I hacked up for my use. 
It's not really fit for general release.
