### ISSUE TITLE
Epubeditor extention for kiwibrowser

### ISSUE THREAD

**Issue by Veaxale** [dteviot/EpubEditor#3]
Can u please make epubeditor extension more compatible with kiwibrowser for mobile user.
Because the browser cant unpack the zip file.
And the extention not loaded at all

**Comment by dteviot** [comment]
@Veaxale 
> And the extention not loaded at all

It's not an extension.  It's just a Web Page.

> Because the browser cant unpack the zip file.

You need to unpack the zip outside of the browser, then open the main.html file in the browser.

**Comment by Veaxale** [comment]
> @Veaxale
> 
> > And the extention not loaded at all
> 
> It's not an extension. It's just a Web Page.
> 
> > Because the browser cant unpack the zip file.
> 
> You need to unpack the zip outside of the browser, then open the main.html file in the browser.

Its seems the mobile browser cant drag n drop the file into it.
Is there will be an option where u can select the file instead of dropping it?.

This below a separate question.
Can i ask about epubmerge.
 is there will be a version for mobile user too?
The webtoepub option library cant be used.

**Comment by dteviot** [comment]
@Veaxale 

Updated versions has been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the instructions at https://github.com/dteviot/EpubEditor and let me know how it goes.

For my notes: 83 minutes work

**Comment by dteviot** [comment]
@Veaxale 

Thanks to gamebeaker, WebToEpub is now available at https://dteviot.github.io/EpubEditor/, no need to download, unpack, etc.  Just browse to the URL and use it.
