### ISSUE TITLE
Mass delete specific tags which appear for every line with epubeditor

### ISSUE THREAD

**Issue by yuzucitrusx** [dteviot/EpubEditor#4]
hi hiii, i'm here to request for a epubeditor script to mass delete these specific **h2, paragraph AND span style tags** that appear for every paragraph on the site -- https://exiledrebelsscanlations.com/, from this original request: https://github.com/dteviot/WebToEpub/issues/1040

i just copied the image from the previous issue and pasted it here too for reference!

![260295770-f2417980-6e62-4307-9d83-0dfe041e9b8a](https://github.com/dteviot/EpubEditor/assets/144674653/26d2a567-cd21-473e-a115-437af3212599)

thank you again! :D

**Comment by shonetypto** [comment]
There’s actually a way to remove all those tags in Calibre or VSC using Regex.

http://stackoverflow.com/questions/43577528/ddg#43578165

its really simple and once you get the hang of it, it takes seconds to clean up epubs.

**Comment by yuzucitrusx** [comment]
@shonetypto

ahhh I'm really not that much of a technical person so I don't know what regex is? I see that mode in Calibre but I dunno how to use it haha, I always preferred using the scripts in epubeditor because it's instantaneous effect with rooting out all possible cases fast 😅  but thank you very much for your help!

**Comment by shonetypto** [comment]
You just enter it in the “find & replace” bar and it finds the code you want to remove. Keep the replace box empty and it will remove what you want for the entire epub. 

The link above is very beginner friendly and already gives you the code. You just have to replace h1 with the codes displayed above. Or you can shorten/change them.

**Comment by dteviot** [comment]
@yuzucitrusx 

This is the script you need
```javascript
let toChange = [...dom.querySelectorAll("h2, p, span")];
for(let s of toChange) {
    s.removeAttribute("style");
}
return 0 < toChange.length;
```

**How to understand this**

```javascript
"h2, p, span"
```

is a CSS selector that says: all &lt;h2&gt; &lt;o&gt; &amp; &lt;style&gt; tags.
(Look up CSS on the internet to explain this.)

```javascript
let toChange = [...dom.querySelectorAll("h2, p, span")];
```

Says: create a list of all &lt;h2&gt;, &lt;p&gt; &amp; &lt;style&gt; tags and call that list "toChange"


```javascript
for(let s of toChange) {
}
```

Says: take each item in the list called "toChange", and do something with it.
Call the item you are currently doing something with "s"
The "do something" goes between the curly brackets.

```javascript
    s.removeAttribute("style");
```

This says remove the style attribute from the something called "s"

So 
```javascript
for(let s of toChange) {
    s.removeAttribute("style");
}
```

Says, remove the style attribute from every tag in the list "toChange"

```javascript
return 0 < toChange.length;
```

This is boilerplate.  What it's doing is telling EpubEditor if any tag was changed.  EpubEditor needs to know if anything was changed, so it can write the changes.

For my notes: 32 minutes work.

**Comment by yuzucitrusx** [comment]
@dteviot 

thank youuuuuu!!! also for the explanation because i was able to delete other tags and their attributes too!! except i couldn't make it work for the "div" tag haha, but the main issue has been resolved! thanks!!!

@shonetypto

and thank you for your input on an alternative method!! i'll give this a shot in calibre too!!

**Comment by dteviot** [comment]
@yuzucitrusx 
>  i couldn't make it work for the "div" tag

Please provide an example

**Comment by yuzucitrusx** [comment]
> Please provide an example

@dteviot 

AH i'm sorry! it was my error with a misplaced variable in the script that i had written incorrectly. but it works properly now for the div tag too! thank you again for your help and explanation!! :D

**Comment by dteviot** [comment]
You are welcome.
Although doing this means
1. With you able to do more, I'll need to do less.
2. In future, I can point other people at this, so they can self help.

**Comment by yuzucitrusx** [comment]
hi hiii! i apologise for the bother again, but i have um another question! if i wanted to delete **both the tags and the text ensconced within the tags themselves**, how can i reform the script to do that? i was looking at the other issue which had a similar request that you referenced and thought it would be the third line that i'd need to change, but couldn't get it right...

```
let toChange = [...dom.querySelectorAll("h2, span")];
for(let s of toChange) {
      s.replaceWith(s.textContent);
}
return 0 < toChange.length;
```

i would like to delete the entire line like shown in the following examples:

```
<span style="color:#222222">text goes here, please delete me too.</span>

<p style="height:1px;width:0;overflow:hidden;display:inline-block">please delete me.</p>
```

**Comment by yuzucitrusx** [comment]
AHH i'm really klutzy, i figured it out a second after posting this, i just made another typo with the variables ahhh, sorry again! i'll delete this comment haha.

**Comment by yuzucitrusx** [comment]
ahhhh im sorry for the bother again, but i actually made another error that wrecked my epub instead. it had actually worked before, but now i cant rewrite the script to do the same thing, about deleting both the tags and the text within the tags as well. probably because there are so many other unnecessary tags i deleted that it affected the span tags too...

example **span style** tag i wanted deleted:

`<span style="#222222">text is here, please delete me too.</span>`

**Comment by dteviot** [comment]
@yuzucitrusx 

To delete the entrie element, including inner content, use the remove() method. https://developer.mozilla.org/en-US/docs/Web/API/Element/remove

Note, if you'd like to see what elements the script is removing, you can add a console.log() command and open the console tab under the developer tools.

To select those span elements, you will want to use an attribute selector.  https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors

So, the CSS should be
```css
span[style="color:#000000"]
```

However, the line in the script needs to enclose the CSS in quotes.  And the selector has quotes.
So, to solve this, you have to put a slash in front of the quotes in the CSS.

So, whole script should be

```javascript
let toChange = [...dom.querySelectorAll("span[style=\"color:#000000\"]")];
for(let s of toChange) {
    console.log(s);
    s.remove();
}
return 0 < toChange.length;
```

Note, I have not tested this script.
If this doesn't work.  Drop me a small epub (say 2 or three chapters) with the problem and I'll figure it out.

**Comment by yuzucitrusx** [comment]
ahhhhh thank you so much again for another explanation, i can now try with other tags with a similar problem! it worked super amazing!! thank you!!! <3
