### ISSUE TITLE
The webpage doesn't respond when used on a mobile phone

### ISSUE THREAD

**Issue by eulaveen** [dteviot/EpubEditor#5]
Hi
I use a mobile phone I tried opening the HTML file with both chrome and kiwi browser, each time I add the epub file to the page nothing happens no further buttons or instructions appear
I tried with other epub files with smaller size
I tried adding jszip.min.js to the same directory
I also tried to just wait but nothing changed
This is all I see
![IMG_20240114_211829](https://github.com/dteviot/EpubEditor/assets/114764978/d6461813-baf3-4fb2-87c7-d475990fac3d)

**Comment by dteviot** [comment]
@eulaveen 
How did you get the HTML file?
Did you download from https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8 and unzip?
In the folder with the HTML file, there should also be several .js files.

**Comment by eulaveen** [comment]
@dteviot I downloaded the zip folder from here then unzip it and followed the steps from "read me" 
I opened the HTML main file in the browser then added the epub file 
If I misunderstood the instructions and I am supposed to do something else please reexplain

**Comment by dteviot** [comment]
@eulaveen 
How did you unzip it?  After unzipping, you should see the following files in the folder:

![image](https://github.com/dteviot/EpubEditor/assets/5157081/f1e760a7-e266-41a7-b467-b25f5741d6ea)


Based on you saying "I tried adding jszip.min.js to the same directory", I think you don't have the .js files.

**Comment by eulaveen** [comment]
@dteviot 
I unzipped it by clicking decompress and got those files clicked on main.html got to the webpage but as I explained nothing happened so then i added jszip.min.js to them and tried again which also didn't work
![IMG_20240114_223733](https://github.com/dteviot/EpubEditor/assets/114764978/9a48be2b-de06-462a-b788-42c052eb17cf)

**Comment by dteviot** [comment]
@eulaveen 
I'm sorry, I'm out of ideas why it doesn't work on your phone.  
The steps do work on a windows desktop.  But the symptoms you give suggest to me that the .js files are not being run by the html.
I've never tried running it on an android device.

Note, I don't know if you have a web server available.  But if you put the files on a server and tried browsing to the .html file, it should work.  (Again, I haven't tried this myself.)

**Comment by eulaveen** [comment]
@dteviot that's fine then I will try using a desktop next time when it available for me 
I don't know about a web server I looked in the play store and a bunch of http servers pop up if that's what you mean I can give it a try too 
Thank you regardless

**Comment by eulaveen** [comment]
@dteviot so I tried the http server and it did work this time not sure why it needs to do all that but it might be related to accessing files permission but I don't know these stuff so might be something else 

Thank you

**Comment by dteviot** [comment]
@eulaveen 

Thanks to gamebeaker, WebToEpub is now available at https://dteviot.github.io/EpubEditor/, no need to download, unpack, etc.
