### ISSUE TITLE
Is it possible to make ePubEditor target only a specific range of xhtml files?

### ISSUE THREAD

**Issue by yuyu-cloud** [dteviot/EpubEditor#6]
Hello, as the subject line asks, I was wondering if I could request a script in epubEditor that would make it so its functions would only be pushed to affect a specific range of xhtml files.  This is because one of the xhtml files happens to also contains the targeted element, but I only want that element to be untouched in _that_ specific xhtml file, and I'd like all other occurrences of that element in all succeeding xhtml files to be fixed up via ePubEditor. I'm not sure if this is feasible, but thought it'd be okay to ask ;)

Thank you~

P.S. Since I have multiple files, continually extracting the one xhtml file before processing the rest in ePubEditor seemed a little laborious, so was looking for a quick fix to this problem xx

**Comment by dteviot** [comment]
@yuyu-cloud 

That sounds rather like a feature just for you.
I can make a custom build for you.  Quick question, does the file have the same name in each epub, or code it differ?
If it's the same, I can save myself some work and hard code it.  If not, it will take more work.

**Comment by yuyu-cloud** [comment]
Haha, yes it would probably be something useful for my needs, albeit a nice overall versatile touch to the program for users who may like specificity. If it's not too much trouble, a custom build alongside the already existing functions (buttons) would be very much appreciated, though if the task is too taxing, that's alright too :)

And to answer your question, I'm a little confused at what you mean. But, if you're asking whether the xhtml file I want to remain **OUT OF RANGE**, as in the sole untouched file, has the same filename. Then, yes, it does for all epubs. The single file I want to not be affected by ePubEditor is collectively labelled as "**Table_of_Contents.xhtml**", whereas all other filenames in succession of it are variable and therefore inconstant. I'm not too certain if this is what you meant? Or are you asking if the external epub's filename itself is the same / different, to which it would be the **latter**. Apologies for my undue confusion :) If I answered wrong, please do ask again~ I'll try to answer correct haha.

**Comment by dteviot** [comment]
@yuyu-cloud 

>  The single file I want to not be affected by ePubEditor is collectively labelled as "Table_of_Contents.xhtml" (including underscores + file extension)

That's what I wanted to know.  Sorry for not being clear.
Attached should do the job.  It will ignore the "Table_of_Contents.xhtml" file in the epub.

**Instructions:** 
1. Extract Epub.js from attached Epub.zip 
2. With existing EpubEditor, replace file Epub.js with file from zip.  Suggestion: backup EpubEditor before doing this.

Tested with: Was only able to test against a mocked up epub file.  (Will need an actual file for further testing if this doesn't work).
For my notes: 40 minutes work
[Epub.zip](https://github.com/user-attachments/files/16452301/Epub.zip)

**Comment by yuyu-cloud** [comment]
Hello! Thank you very much, this did the job just as I wanted :)

But, if it's not too much trouble to ask a question, you had mentioned that this was hard-coded where you had specificated the exact input to ignore. Though, if you were to configure the epub.js file to be soft-coded, thereby allowing users to effectuate a different variable that the program can ignore for each instance, how would you perhaps go about implementing this? Just method-wise, since you had mentioned it requires a more complex process to doing so.  How would the user be able to input the "specific range" through ePubEditor to ensure that those files remain unaffected when the epub file itself is processed? Overall, what would the estimated time to complete the soft-coded version be?

Hoping these questions aren't an inconvenience to you, just wanted to know for furture reference~ xx Thank you again for your time!!

**Comment by dteviot** [comment]
@yuyu-cloud 
> how would you perhaps go about implementing this

1. Add new text box and control onto web page to get the name.  (Explaining what it does for most users will be tricky.)
2. Plumb the user's input from the control through the code to the point where EpubEditor walks the list of XHTML files.
3. (Optional bonus.)  Error handling/logging, so that someone can figure out why the input they've given doesn't work.

1 and 2 are maybe an hour's work, if I don't care about making what it does understandable.
3 is "I have no idea at this time, but possibly not small."

**Comment by dteviot** [comment]
@yuyu-cloud 

Note, you can modify the file to ignore yourself, it's this line here in Epub.js.
https://github.com/dteviot/EpubEditor/blob/ad37c068162972ed9b278c1a4973333ea90534df/Epub.js#L360

**Comment by yuyu-cloud** [comment]
Ohhh, I see! Thank you very much for taking the time to answer my questions and for pointing out which exact line in the js file carries the specificated input that can be altered for different instances, it's super helpful! :)
