### ISSUE TITLE
No button Appears/Console Error

### ISSUE THREAD

**Issue by KDJ1863** [dteviot/EpubEditor#7]
Afer uploading an epub, no button appears. HTML file ran on Chrome. Console shows 
```html
ReferenceError: Epub is not defined
    at new Main (main.js:5:25)
    at main.js:211:12Understand this error
```

**Comment by dteviot** [comment]
@KDJ1863 

The error message suggests the file Epub.js is not in the same directory as the files main.html and main.js.
I'm guessing you misunderstood either:
* unpack the zip file, or
* Open main.html in Chrome.

Can you describe exactly what you did in I way I can reproduce your steps?
e.g. What steps did you take to do the above?

**Comment by dteviot** [comment]
@KDJ1863 

Thanks to gamebeaker, WebToEpub is now available at https://dteviot.github.io/EpubEditor/, no need to download, unpack, etc.  Just browse to the above URL and use.
