### ISSUE TITLE
github.io

### ISSUE THREAD

**Issue by gamebeaker** [dteviot/EpubEditor#8]
Is it possible to publish EpubEditor as an online Webpage same as https://github.com/dteviot/dteviot.github.io or https://dteviot.github.io/?

**Comment by dteviot** [comment]
@gamebeaker 
I'm not sure.  It requires javascript, and I don't know how you include javascript on the GitHub webpages.  It might be as simple as using &lt;script&gt; tags on the page.  I did a quick search and didn't see an answer.

**Comment by dteviot** [comment]
Thanks to gamebeaker, WebToEpub is now available at https://dteviot.github.io/EpubEditor/, no need to download, unpack, etc.
